spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:13306/qsmy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: qsmy0424
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:13306/wwhm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: qsmy0424
      driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true